CREATE TABLE EMPLOYEES (
        EMPLOYEE_ID NUMBER (6) NOT NULL,
        FIRST_NAME VARCHAR2 (20 BYTE),
        LAST_NAME VARCHAR2 (25 BYTE) NOT NULL,
        EMAIL VARCHAR2 (25 BYTE) NOT NULL,
        PHONE_NUMBER VARCHAR2 (20 BYTE),
        HIRE_DATE DATE NOT NULL,
        JOB_ID VARCHAR2 (10 BYTE) NOT NULL,
        SALARY NUMBER (8,2),
        COMMISSION_PCT NUMBER (2,2),
        MANAGER_ID NUMBER (6),
        DEPARTMENT_ID NUMBER (4)
      );

      CREATE TABLE JOBS (
        JOB_ID VARCHAR2 (10 BYTE) NOT NULL,
        JOB_TITLE VARCHAR2 (35 BYTE) NOT NULL,
        MIN_SALARY NUMBER (6),
        MAX_SALARY NUMBER (6),
        CONSTRAINT JOB_ID_UK UNIQUE (JOB_ID)
      ) LOGGING;


      ALTER TABLE EMPLOYEES ADD CONSTRAINT employee_id_pk PRIMARY KEY (EMPLOYEE_ID);
      ALTER TABLE EMPLOYEES ADD CONSTRAINT job_id_fk FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID);
      ALTER TABLE EMPLOYEES ADD CONSTRAINT email_unique UNIQUE (EMAIL);
      ALTER TABLE EMPLOYEES ADD CONSTRAINT salary_min_check CHECK (salary > 0);
      ALTER TABLE EMPLOYEES MODIFY DEPARTMENT_ID CONSTRAINT department_id_nn NOT NULL;

      ALTER TABLE EMPLOYEES DROP CONSTRAINT employee_id_pk;
      ALTER TABLE EMPLOYEES DROP CONSTRAINT job_id_fk;
      ALTER TABLE EMPLOYEES DROP CONSTRAINT email_unique;
      ALTER TABLE EMPLOYEES DROP CONSTRAINT salary_min_check;
      ALTER TABLE EMPLOYEES DROP CONSTRAINT department_id_nn;

      ALTER TABLE EMPLOYEES ADD CONSTRAINT phone_number_unique UNIQUE (PHONE_NUMBER);
      ALTER TABLE JOBS DROP CONSTRAINT phone_number_unique;

      ALTER TABLE EMPLOYEES DROP CONSTRAINT not_exist;

      ALTER TABLE EMPLOYEES ADD CONSTRAINT department_id_check CHECK (DEPARTMENT_ID > 0);
      ALTER TABLE NOT_EXIST DROP CONSTRAINT department_id_check;

      ALTER TABLE NOT_EXIST DROP CONSTRAINT not_exist;