CREATE TABLE table_t1_11_27_2018_2_26 (
  JOB_ID VARCHAR2 (10 BYTE) NOT NULL,
  JOB_TITLE VARCHAR2 (35 BYTE) NOT NULL,
  MIN_SALARY NUMBER (6),
  MAX_SALARY NUMBER (6),
  CONSTRAINT JOB_SALARY CHECK (MIN_SALARY > 0 AND MAX_SALARY < 1000 AND MAX_SALARY > MIN_SALARY),
  CONSTRAINT JOB_TITLE CHECK ("JOB_TITLE"='"R&D"')
);